owner: aibeatz
repo: upptime
sites:
  - name: AIBeatz
    url: https://app.aibeatz.com
  - name: Sound
    url: $SOUND_URL
  - name: Dataset
    url: $DATASET_URL
#  - name: Compose
#    url: $COMPOSE_URL
#  - name: Synthesize
#    url: $SYNTHESIZE_URL
status-website:
  cname: uptime.aibeatz.com
  logoUrl: https://app.aibeatz.com/images/signet.png
  favicon: https://app.aibeatz.com/images/favicon.png
  name: AIBeatz uptimes
  introTitle: "**AIBeatz** uptime monitor."
  introMessage: Current status of all services:
  navbar:
    - title: Status
      href: /
    - title: AIBeatz
      href: https://app.aibeatz.com/
