owner: aibeatz
repo: upptime
sites:
  - name: AIBeatz
    url: https://aibeatz.com
  - name: Sound
    url: $SOUND_URL
  - name: Dataset
    url: $DATASET_URL
#  - name: Compose
#    url: $COMPOSE_URL
status-website:
  name: AIBeatz uptimes
  cname: uptime.aibeatz.com
  logoUrl: https://aibeatz.com/logo-32x32.png
  favicon: https://aibeatz.com/favicon.ico
  introTitle: "**AIBeatz** uptime monitor."
  introMessage: "Current status of all services:"
  navbar:
    - title: Status
      href: /
    - title: AIBeatz
      href: https://aibeatz.com/
